name: Validate Pull Request

on:
  pull_request:

jobs:
  merge-validation:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: All checks passed
        run: true


  ci:
    uses: "./.github/workflows/storybook-ci.yml"
      