name: Validate Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  merge-validation:
    runs-on: ubuntu-latest
    if: always() && !contains(join(needs.*.result, ','), 'failure')
    needs: storybook-ci
    steps:
      - name: Log Results
        shell: pwsh
        run: |
          Write-Host "Dependency Results: ${{ join(needs.*.result, ',') }}"
          Write-Host "Dependency Results: ${{ needs }}"

      - name: Generate Deployment Summary
        run: |
          "Merge Validation Results" >> $env:GITHUB_STEP_SUMMARY
          "" >> $env:GITHUB_STEP_SUMMARY
          ("${{ needs }}" | ConvertFrom-Json).psobject.Properties | ForEach-Object {
              "- $($_.name) $($_.value.result) >> $env:GITHUB_STEP_SUMMARY
          }

  changes: 
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.storybook }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          storybook:
            - '.github/workflows/storybook*.*'
            - '.storybook/**'
            - 'stories/**'
            - 'package*.json'

  storybook-ci:
    needs: changes
    if: ${{ needs.changes.outputs.storybook == 'true' }}
    uses: "./.github/workflows/storybook-ci.yml"
