name: Validate Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  merge-validation:
    runs-on: ubuntu-latest
    needs: storybook-ci
    if: ${{ contains(join(needs.*.result, ','), 'success') || contains(join(needs.*.result, ','), 'skipped') }}
    steps:
      - name: All checks passed
        run: "true"

  changes: 
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.storybook }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          storybook:
            - '.github/workflows/storybook*.*'
            - '.storybook/**'
            - 'stories/**'
            - 'package*.json'

  storybook-ci:
    needs: changes
    if: ${{ needs.changes.outputs.storybook == 'true' }}
    uses: "./.github/workflows/storybook-ci.yml"
